In [44]:
import pandas as pd
import csv
import datetime

dfa=pd.read_csv(r'C:\Users\smrut\Documents\Python\PythonAssignment3\Assignment 3\Data\employee_compensation.csv',sep=",")
aim=dfa[dfa.Year Type=='Calendar']
#dfa.head()
aim

SyntaxError: invalid syntax (<ipython-input-44-80ddde54f3aa>, line 6)

In [23]:
dfb=dfa.rename(columns = {'Total Compensation':'Total_Compensation','Total benefits':'Total_Benefits','Other Benefits' : 'Other_Benefits','Total Salary':'Total_Salary','Employee Identifier':'Employee_Identifier','Total Benefits':'Total_Benefits','Year Type':'Year_Type'})

dfb.head()

,Year_Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,...,Employee_Identifier,Salaries,Overtime,Other Salaries,Total_Salary,Retirement,Health/Dental,Other_Benefits,Total_Benefits,Total_Compensation
0,Calendar,2013,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
1,Fiscal,2015,4,Community Health,DPH,Public Health,790.0,"SEIU - Miscellaneous, Local 1021",2600,Dietary & Food,...,52950,69169.82,755.02,4179.08,74103.92,15641.92,12499.30,5669.02,33810.24,107914.16
2,Calendar,2016,3,Human Welfare & Neighborhood Development,WOM,Department of the Status of Women,323.0,Members of Boards and Commissions,0900,Management,...,33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,6,General Administration & Finance,HRD,Human Resources,790.0,"SEIU - Miscellaneous, Local 1021",8100,Legal & Court,...,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
4,Fiscal,2015,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,15849,1102.50,0.00,0.00,1102.50,0.00,538.82,85.36,624.18,1726.68

In [43]:
dfb=dfb.loc[dfb.Year_Type=="Calendar"]
dfb.head()

Empty DataFrame
Columns: [Year_Type, Year, Organization Group Code, Organization Group, Department Code, Department, Union Code, Union, Job Family Code, Job Family, Job Code, Job, Employee_Identifier, Salaries, Overtime, Other Salaries, Total_Salary, Retirement, Health/Dental, Other_Benefits, Total_Benefits, Total_Compensation, Mean Total_Compensation, Mean Total_Benefits, Mean Total_Salary, Mean Other_Benefits, PERCENT TOTAL BENEFITS]
Index: []

[0 rows x 27 columns]

In [30]:
dfb['Mean Total_Compensation']=pd.DataFrame(dfb.groupby('Employee_Identifier').Total_Compensation.mean())
dfb['Mean Total_Benefits']=pd.DataFrame(dfb.groupby('Employee_Identifier').Total_Benefits.mean())
dfb['Mean Total_Salary']=pd.DataFrame(dfb.groupby('Employee_Identifier').Total_Salary.mean())
dfb['Mean Other_Benefits']=pd.DataFrame(dfb.groupby('Employee_Identifier').Other_Benefits.mean())
dfb['Mean Total_Compensation']=pd.DataFrame(dfb.groupby('Employee_Identifier').Total_Compensation.mean())
dfb.head()

Empty DataFrame
Columns: [Year_Type, Year, Organization Group Code, Organization Group, Department Code, Department, Union Code, Union, Job Family Code, Job Family, Job Code, Job, Employee_Identifier, Salaries, Overtime, Other Salaries, Total_Salary, Retirement, Health/Dental, Other_Benefits, Total_Benefits, Total_Compensation, Mean Total_Compensation, Mean Total_Benefits, Mean Total_Salary, Mean Other_Benefits, PERCENT TOTAL BENEFITS]
Index: []

[0 rows x 27 columns]

In [25]:
dfb['PERCENT TOTAL BENEFITS'] = (dfb['Total_Salary'] / dfb['Total_Compensation']) *100
dfb.head()

,Year_Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,...,Retirement,Health/Dental,Other_Benefits,Total_Benefits,Total_Compensation,Mean Total_Compensation,Mean Total_Benefits,Mean Total_Salary,Mean Other_Benefits,PERCENT TOTAL BENEFITS
0,Calendar,2013,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,20142.55,12918.24,8371.76,41432.55,143916.66,NaN,NaN,NaN,NaN,71.210734
1,Fiscal,2015,4,Community Health,DPH,Public Health,790.0,"SEIU - Miscellaneous, Local 1021",2600,Dietary & Food,...,15641.92,12499.30,5669.02,33810.24,107914.16,66570.3600,22192.881667,44377.478333,3500.180,68.669320
2,Calendar,2016,3,Human Welfare & Neighborhood Development,WOM,Department of the Status of Women,323.0,Members of Boards and Commissions,0900,Management,...,0.00,51.45,15.83,67.28,267.28,15780.5950,4718.895000,11061.700000,853.530,74.827896
3,Calendar,2016,6,General Administration & Finance,HRD,Human Resources,790.0,"SEIU - Miscellaneous, Local 1021",8100,Legal & Court,...,325.05,257.23,153.85,736.13,2519.13,41103.0100,12889.050000,28213.960000,2288.695,70.778404
4,Fiscal,2015,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,0.00,538.82,85.36,624.18,1726.68,26427.9925,7643.112500,18784.880000,1448.095,63.850858

In [27]:
dfb=dfb[dfb.Year_Type=='Calendar']
dfb.head()

Empty DataFrame
Columns: [Year_Type, Year, Organization Group Code, Organization Group, Department Code, Department, Union Code, Union, Job Family Code, Job Family, Job Code, Job, Employee_Identifier, Salaries, Overtime, Other Salaries, Total_Salary, Retirement, Health/Dental, Other_Benefits, Total_Benefits, Total_Compensation, Mean Total_Compensation, Mean Total_Benefits, Mean Total_Salary, Mean Other_Benefits, PERCENT TOTAL BENEFITS]
Index: []

[0 rows x 27 columns]