In [16]:
import csv
import pandas as pd

from pandas import DataFrame
import numpy as np

In [35]:
dfa=pd.read_csv('movies_awards.csv')
dfa = dfa.fillna(value=False)
dfa.head()

,totalSeasons,Plot,Rated,Response,Language,Title,Country,Writer,Metascore,imdbRating,...,Released,Actors,Year,Genre,Awards,Runtime,Type,Poster,imdbVotes,imdbID
0,none,False,False,True,English,Book of Love: The Definitive Reason Why Men Ar...,USA,Jeffrey W. Byrd; Eric George,0.0,6.6,...,14 Feb 2002,40 Glocc; Angelle Brooks; David Brown; Qadr Ca...,2002,Romance; Comedy,False,91 min,movie,False,79.0,tt0156376
1,none,False,False,True,Swedish,Anderssons älskarinna,Sweden,False,0.0,7.4,...,12 Feb 2001,Jakob Eklund; Ebba Forsberg; Örjan Landström; ...,2001,Drama,False,347 min,movie,False,34.0,tt0201374
2,none,False,False,True,English,Bad Blood,UK,Tony Marchant,0.0,5.6,...,11 Jan 2001,Emilia Fox; Serban Celea; Alex Jennings; Steve...,2001,False,False,False,movie,False,8.0,tt0207989
3,none,A historical classic drama in three acts; reto...,False,True,Portuguese,Who Are You?,Portugal,João Botelho; Almeida Garrett (play),0.0,6.1,...,23 Nov 2001,Patrícia Guerreiro; Suzana Borges; Rui Morisso...,2001,Drama; History,1 win & 2 nominations.,112 min,movie,http://ia.media-imdb.com/images/M/MV5BMTM1Mjdi...,189.0,tt0210930
4,none,A father (Williams) suspects his son (Jackson)...,R,True,English,Skeletons in the Closet,USA,Donna Powers; Wayne Powers,0.0,5.4,...,24 Jul 2001,Treat Williams; Linda Hamilton; Jonathan Jacks...,2001,Crime; Drama; Mystery,1 win.,100 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA0NjA2...,603.0,tt0212513

In [33]:
import re

In [104]:
dfa['Awards Won']= dfa['Awards'].str.extract('(\d) win', expand=True).rest_index()
dfa['Awards Nominated ']=dfa['Awards'].str.extract('(\d) nomination', expand=True).reset_index()
dfa['Prime_Awards_Nominated ']=dfa['Awards'].str.extract('Nominated for (\d) Primetime', expand=True).reset_index()
dfa['Oscar_Awards_Nominated ']=dfa['Awards'].str.extract('Nominated for (\d) Oscar', expand=True).reset_index
dfa['Oscar_Awards_Won ']=dfa['Awards'].str.extract('Won (\d) Oscar', expand=True).reset_index()
dfa['Prime_Awards_Won ']=dfa['Awards'].str.extract('Won (\d) Primetime', expand=True).reset_index()
dfa['BAFTA_Awards_Nominated ']=dfa['Awards'].str.extract('Nominated for (\d) BAFTA Film', expand=True).reset_index
dfa['Golden_Globe_Nominated ']=dfa['Awards'].str.extract('Nominated for (\d) Golden Globe', expand=True).reset_index
dfa['Golden_Globe_Nominated ']=dfa['Awards'].str.extract('Won (\d) Golden Globe', expand=True).reset_index()

#dfa['Total Awards Won or Nominated'] = dfa[['Awards Won','Awards Nominated']].sum(axis=1)


#dfa['Total Awards Won or Nominated'] = dfa.fillna(0)['Awards Won'] + dfa.fillna(0)['Awards Nominated']

#dfa['Awards Nominated ']=dfa['Awards'].str.extract('(\d) nominations.', expand=True)
#dfa['Awards Nominated ']=dfa['Awards'].str.extract('(\d) nominations.', expand=True)

dfa

ValueError: Wrong number of items passed 2, placement implies 1

TypeError: Expected list, got tuple

In [100]:
dfa.drop(dfa.columns[[29]], axis=1, inplace=True)

In [103]:
dfa.drop(dfa.columns[[21]], axis=1, inplace=True)
dfa

,totalSeasons,Plot,Rated,Response,Language,Title,Country,Writer,Metascore,imdbRating,...,Runtime,Type,Poster,imdbVotes,imdbID,Prime_Awards_Nominated,Oscar_Awards_Nominated,Oscar_Awards_Won,Prime_Awards_Won,BAFTA_Awards_Nominated
0,none,False,False,True,English,Book of Love: The Definitive Reason Why Men Ar...,USA,Jeffrey W. Byrd; Eric George,0.0,6.6,...,91 min,movie,False,79.0,tt0156376,0,<bound method DataFrame.reset_index of ...,0,0,<bound method DataFrame.reset_index of ...
1,none,False,False,True,Swedish,Anderssons älskarinna,Sweden,False,0.0,7.4,...,347 min,movie,False,34.0,tt0201374,1,<bound method DataFrame.reset_index of ...,1,1,<bound method DataFrame.reset_index of ...
2,none,False,False,True,English,Bad Blood,UK,Tony Marchant,0.0,5.6,...,False,movie,False,8.0,tt0207989,2,<bound method DataFrame.reset_index of ...,2,2,<bound method DataFrame.reset_index of ...
3,none,A historical classic drama in three acts; reto...,False,True,Portuguese,Who Are You?,Portugal,João Botelho; Almeida Garrett (play),0.0,6.1,...,112 min,movie,http://ia.media-imdb.com/images/M/MV5BMTM1Mjdi...,189.0,tt0210930,3,<bound method DataFrame.reset_index of ...,3,3,<bound method DataFrame.reset_index of ...
4,none,A father (Williams) suspects his son (Jackson)...,R,True,English,Skeletons in the Closet,USA,Donna Powers; Wayne Powers,0.0,5.4,...,100 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA0NjA2...,603.0,tt0212513,4,<bound method DataFrame.reset_index of ...,4,4,<bound method DataFrame.reset_index of ...
5,none,Four perky; clueless cheerleaders from the Hap...,R,True,English,Cheerleader Ninjas,USA,Kevin Campbell,0.0,2.3,...,91 min,movie,http://ia.media-imdb.com/images/M/MV5BMjA3MTQ1...,881.0,tt0235280,5,<bound method DataFrame.reset_index of ...,5,5,<bound method DataFrame.reset_index of ...
6,none,Sandrine; a woman in her thirties gets tired o...,False,True,French,The Girl from Paris,France,Christian Carion; Eric Assous,64.0,6.8,...,103 min,movie,https://images-na.ssl-images-amazon.com/images...,1715.0,tt0240149,6,<bound method DataFrame.reset_index of ...,6,6,<bound method DataFrame.reset_index of ...
7,none,A rivalry develops between a showbiz veteran a...,R,True,English,The Final Curtain,UK; USA,John Hodge,0.0,5.8,...,85 min,movie,http://ia.media-imdb.com/images/M/MV5BOGI4MmIw...,466.0,tt0243904,7,<bound method DataFrame.reset_index of ...,7,7,<bound method DataFrame.reset_index of ...
8,none,Three female friends behave badly.,R,True,English; French,Crush,UK; Germany,John McKay,37.0,5.8,...,108 min,movie,https://images-na.ssl-images-amazon.com/images...,3253.0,tt0245407,8,<bound method DataFrame.reset_index of ...,8,8,<bound method DataFrame.reset_index of ...
9,none,"An adaptation of Keith Laumer's short story; ""...",False,True,English,Happy Birthday,USA,Crispin Whittell,0.0,4.3,...,False,movie,False,63.0,tt0245932,9,<bound method DataFrame.reset_index of ...,9,9,<bound method DataFrame.reset_index of ...
10,none,A handful of human and alien survivors trapped...,False,True,English,Run Like Hell,USA,Rusty Buchert; Brian Freyermuth,0.0,8.4,...,False,game,False,62.0,tt0246902,10,<bound method DataFrame.reset_index of ...,10,10,<bound method DataFrame.reset_index of ...
11,none,At Pacific Palisades High; a poor Latino falls...,PG-13,True,English,Crazy/Beautiful,USA,Phil Hay; Matt Manfredi,61.0,6.5,...,99 min,movie,https://images-na.ssl-images-amazon.com/images...,21612.0,tt0250224,11,<bound method DataFrame.reset_index of ...,11,11,<bound method DataFrame.reset_index of ...
12,none,A young wife's religious faith is shaken when ...,False,True,English,A Death in the Family,USA,James Agee (novel); Robert W. Lenski (teleplay),0.0,6.2,...,91 min,movie,https://images-na.ssl-images-amazon.com/images...,96.0,tt0251042,12,<bound method DataFrame.reset_index of ...,12,12,<bound method DataFrame.reset_index of ...
13,none,Love is complex and relationships deteriorate.,R,True,English,The Anniversary Party,USA,Jennifer Jason Leigh; Alan Cumming,56.0,6.4,...,115 min,movie,http://ia.media-imdb.com/images/M/MV5BMzY1NjM2...,7412.0,tt0254099,13,<bound method DataFrame.reset_index of ...,13,13,<bound method DataFrame.reset_index of ...
14,1,False,False,True,English,Life as We Know It,UK,False,0.0,6.8,...,False,series,False,10.0,tt0257306,14,<bound method DataFrame.reset_index of ...,14,14,<bound method DataFrame.reset_index of ...
15,none,An older British reporter vies with a young U....,R,True,English; French; Vietnamese,The Quiet American,UK; Germany; USA; Australia; France,Graham Greene (novel); Christopher Hampton (sc...,84.0,7.1,...,101 min,movie,https://images-na.ssl-images-amazon.com/images...,24178.0,tt0258068,15,<bound method DataFrame.reset_index of ...,15,15,<bound method DataFrame.reset_index of ...
16,2,The lives and work of the staff of a New York ...,False,True,English,100 Centre Street,USA,False,0.0,7.8,...,60 min,series,https://images-na.ssl-images-amazon.com/images...,133.0,tt0260596,16,<bound method DataFrame.reset_index of ...,16,16,<bound method DataFrame.reset_index of ...
17,none,False,False,True,Spanish,90-60-90,Colombia,False,0.0,0.0,...,False,movie,False,0.0,tt0261507,17,<bound method DataFrame.reset_index of ...,17,17,<bound method DataFrame.reset_index of ...
18,none,The neighborhood La Estrella; in Bogotá; is in...,False,True,Spanish,Like Cat and Mouse,France; Colombia,Jörg Hiller,0.0,6.7,...,95 min,movie,https://images-na.ssl-images-amazon.com/images...,119.0,tt0263017,18,<bound method DataFrame.reset_index of ...,18,18,<bound method DataFrame.reset_index of ...
19,none,A group of Irish noblemen kidnap girls in orde...,False,True,English; Italian,The Abduction Club,UK; France; Ireland; Germany,Bill Britten; Richard Crawford,0.0,6.8,...,96 min,movie,https://images-na.ssl-images-amazon.com/images...,1497.0,tt0264333,19,<bound method DataFrame.reset_index of ...,19,19,<bound method DataFrame.reset_index of ...
20,none,After being released from an Italian prison; B...,False,True,English,In Love and War,USA,Eric Newby (book); John Mortimer (teleplay),0.0,6.7,...,90 min,movie,https://images-na.ssl-images-amazon.com/images...,269.0,tt0267693,20,<bound method DataFrame.reset_index of ...,20,20,<bound method DataFrame.reset_index of ...
21,none,Greed; betrayal and vengeance set the stage fo...,False,True,English,The Sign of Four,Canada,Arthur Conan Doyle (novel); Joe Wiesenfeld,0.0,6.2,...,90 min,movie,https://images-na.ssl-images-amazon.com/images...,415.0,tt0270645,21,<bound method DataFrame.reset_index of ...,21,21,<bound method DataFrame.reset_index of ...
22,False,The world's most uncomfortably awkward deluded...,False,True,English,Adrian Mole: The Cappuccino Years,UK,False,0.0,7.0,...,30 min,series,http://ia.media-imdb.com/images/M/MV5BMzU0ZjQy...,98.0,tt0271275,22,<bound method DataFrame.reset_index of ...,22,22,<bound method DataFrame.reset_index of ...
23,1,False,False,True,Spanish,Amores querer con alevosía,Mexico,False,0.0,7.1,...,False,series,False,14.0,tt0271896,23,<bound method DataFrame.reset_index of ...,23,23,<bound method DataFrame.reset_index of ...
24,none,A psychologically troubled novelty supplier is...,R,True,English,Punch-Drunk Love,USA,Paul Thomas Anderson,78.0,7.3,...,95 min,movie,https://images-na.ssl-images-amazon.com/images...,112174.0,tt0272338,24,<bound method DataFrame.reset_index of ...,24,24,<bound method DataFrame.reset_index of ...
25,none,Great and important movie about the German-Ger...,False,True,German,Romeo,Germany,Ruth Toma,0.0,6.7,...,88 min,movie,False,37.0,tt0274768,25,<bound method DataFrame.reset_index of ...,25,25,<bound method DataFrame.reset_index of ...
26,none,"With his radio blaring Three Dog Night's ""Neve...",False,True,English,The Kiss,USA,Anthony Russo; Joe Russo,0.0,6.1,...,8 min,movie,False,31.0,tt0275458,26,<bound method DataFrame.reset_index of ...,26,26,<bound method DataFrame.reset_index of ...
27,False,False,False,True,French,Avoir su...,Canada,False,0.0,0.0,...,False,series,False,0.0,tt0275823,27,<bound method DataFrame.reset_index of ...,27,27,<bound method DataFrame.reset_index of ...
28,1,False,False,True,Spanish,Academia de baile Gloria,Spain,False,0.0,0.0,...,False,series,False,0.0,tt0276639,28,<bound method DataFrame.reset_index of ...,28,28,<bound method DataFrame.reset_index of ...
29,none,Cet Amour-là is an intimate portrait of a lege...,UNRATED,True,French,Cet amour-là,France,Yann Andréa (novel); Josée Dayan (adaptation);...,57.0,6.3,...,100 min,movie,https://images-na.ssl-images-amazon.com/images...,300.0,tt0277622,29,<bound method DataFrame.reset_index of ...,29,29,<bound method DataFrame.reset_index of ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15357,1,Maya falls in love with Arjun while working on...,False,True,Hindi,Beyhadh,India,Ritika Bajaj Vijra,0.0,8.1,...,22 min,series,https://images-na.ssl-images-amazon.com/images...,101.0,tt6193550,15357,<bound method DataFrame.reset_index of ...,15357,15357,<bound method DataFrame.reset_index of ...
15358,False,False,False,True,Norwegian,BroShow,Norway,False,0.0,0.0,...,False,series,False,0.0,tt6195514,15358,<bound method DataFrame.reset_index of ...,15358,15358,<bound method DataFrame.reset_index of ...
15359,none,Interviews and behind-the-scenes with the cast...,False,True,English,Lost Souls: On the Road with 'Blood Father',USA,False,0.0,0.0,...,28 min,movie,False,0.0,tt6200872,15359,<bound method DataFrame.reset_index of ...,15359,15359,<bound method DataFrame.reset_index of ...
15360,none,The sisters of the Delta Omega sorority won a ...,False,True,English,Hot Tub Party Massacre,Canada,Chris Greenaway,0.0,8.7,...,72 min,movie,https://images-na.ssl-images-amazon.com/images...,7.0,tt6203954,15360,<bound method DataFrame.reset_index of ...,15360,15360,<bound method DataFrame.reset_index of ...
15361,False,False,False,True,Dutch,All in Kitchen,Netherlands,False,0.0,0.0,...,False,series,https://images-na.ssl-images-amazon.com/images...,0.0,tt6207286,15361,<bound method DataFrame.reset_index of ...,15361,15361,<bound method DataFrame.reset_index of ...
15362,none,A young boy in the suburbs is haunted by his s...,False,True,English,Alex,USA,Kearns Sean,0.0,0.0,...,False,movie,https://images-na.ssl-images-amazon.com/images...,0.0,tt6207542,15362,<bound method DataFrame.reset_index of ...,15362,15362,<bound method DataFrame.reset_index of ...
15363,none,False,False,True,English,All Access Nashville: Celebrating the CMA Awar...,USA,False,0.0,0.0,...,60 min,movie,False,0.0,tt6208454,15363,<bound method DataFrame.reset_index of ...,15363,15363,<bound method DataFrame.reset_index of ...
15364,False,False,False,True,False,When a Snail Falls in Love,False,False,0.0,0.0,...,False,series,False,0.0,tt6209406,15364,<bound method DataFrame.reset_index of ...,15364,15364,<bound method DataFrame.reset_index of ...
15365,False,Celebrities from all avenues react to viral vi...,False,True,English,Celebs React,USA,False,0.0,0.0,...,24 min,series,https://images-na.ssl-images-amazon.com/images...,0.0,tt6214762,15365,<bound method DataFrame.reset_index of ...,15365,15365,<bound method DataFrame.reset_index of ...
15366,False,False,False,True,English,Catching Kelce,USA,False,0.0,0.0,...,False,series,https://images-na.ssl-images-amazon.com/images...,0.0,tt6218734,15366,<bound method DataFrame.reset_index of ...,15366,15366,<bound method DataFrame.reset_index of ...
15367,none,Armenia is a cinematic interweaving of film; l...,False,True,English,Armenia,Germany; France; Armenia,M.A. Littler,0.0,0.0,...,84 min,movie,https://images-na.ssl-images-amazon.com/images...,0.0,tt6224832,15367,<bound method DataFrame.reset_index of ...,15367,15367,<bound method DataFrame.reset_index of ...
15368,False,False,False,True,English,Boss!,UK,False,0.0,0.0,...,False,series,False,0.0,tt6225248,15368,<bound method DataFrame.reset_index of ...,15368,15368,<bound method DataFrame.reset_index of ...
15369,none,As the zombies storyline draws to a close; the...,False,True,English,Call of Duty: Revelations,USA,Jason Blundell (story); Craig Houston; Corky L...,0.0,8.7,...,False,game,https://images-na.ssl-images-amazon.com/images...,6.0,tt6225778,15369,<bound method DataFrame.reset_index of ...,15369,15369,<bound method DataFrame.reset_index of ...
15370,False,Documentary series exploring the everyday live...,False,True,English,China: Between Clouds and Dreams,UK,False,0.0,0.0,...,False,series,False,0.0,tt6226174,15370,<bound method DataFrame.reset_index of ...,15370,15370,<bound method DataFrame.reset_index of ...
15371,none,four friends (manman; lady ;cornbread;sammy) 4...,False,True,English,Fresh Off the Porch,USA,Kenneth Blanchard,0.0,0.0,...,80 min,movie,False,0.0,tt6227880,15371,<bound method DataFrame.reset_index of ...,15371,15371,<bound method DataFrame.reset_index of ...
15372,1,A dysfunctional family gathers together during...,False,True,English,Thanksgiving,USA,Bethany Hall; Daniel Powell,0.0,0.0,...,False,series,https://images-na.ssl-images-amazon.com/images...,0.0,tt6237114,15372,<bound method DataFrame.reset_index of ...,15372,15372,<bound method DataFrame.reset_index of ...
15373,none,Nearly 10;000 children in Britain visit a pare...,False,True,English,Prison; My Parents & Me,UK,False,0.0,0.0,...,60 min,movie,False,0.0,tt6239680,15373,<bound method DataFrame.reset_index of ...,15373,15373,<bound method DataFrame.reset_index of ...
15374,none,My parents had only 3 sons; they really wanted...,False,True,False,Sara,Iran,False,0.0,0.0,...,62 min,movie,False,0.0,tt6242742,15374,<bound method DataFrame.reset_index of ...,15374,15374,<bound method DataFrame.reset_index of ...
15375,none,After the death of two of her classmates; Juli...,False,True,Spanish,Elegy,Spain,False,0.0,0.0,...,16 min,movie,False,0.0,tt6242796,15375,<bound method DataFrame.reset_index of ...,15375,15375,<bound method DataFrame.reset_index of ...
15376,False,False,False,True,False,Continent 7: Antarctica,False,False,0.0,0.0,...,False,series,False,0.0,tt6244108,15376,<bound method DataFrame.reset_index of ...,15376,15376,<bound method DataFrame.reset_index of ...
15377,none,False,False,True,False,Thank You,False,False,0.0,0.0,...,False,movie,False,0.0,tt6246446,15377,<bound method DataFrame.reset_index of ...,15377,15377,<bound method DataFrame.reset_index of ...
15378,False,False,False,True,English,Black Is the New Black,UK,False,0.0,0.0,...,120 min,series,False,0.0,tt6249848,15378,<bound method DataFrame.reset_index of ...,15378,15378,<bound method DataFrame.reset_index of ...
15379,False,An Asian American entertainment show covering ...,False,True,English,Asian Entertainment Tonight,USA,Sinakhone Keodara,0.0,0.0,...,44 min,series,https://images-na.ssl-images-amazon.com/images...,0.0,tt6260048,15379,<bound method DataFrame.reset_index of ...,15379,15379,<bound method DataFrame.reset_index of ...
15380,none,False,False,True,Japanese,Dragon Ball: Xenoverse 2,Japan,Akira Toriyama (original story),0.0,8.1,...,False,game,https://images-na.ssl-images-amazon.com/images...,10.0,tt6264336,15380,<bound method DataFrame.reset_index of ...,15380,15380,<bound method DataFrame.reset_index of ...
15381,False,False,False,True,English,Back in Time for Brixton,UK,False,0.0,0.0,...,False,series,False,0.0,tt6268342,15381,<bound method DataFrame.reset_index of ...,15381,15381,<bound method DataFrame.reset_index of ...
15382,none,False,False,True,English,BET Presents Love & Happiness: An Obama Celebr...,USA,False,0.0,0.0,...,False,movie,False,0.0,tt6269718,15382,<bound method DataFrame.reset_index of ...,15382,15382,<bound method DataFrame.reset_index of ...
15383,none,False,False,True,English,The Plague,USA,Devon Metzger (contributing writer); Emir Skal...,0.0,0.0,...,74 min,movie,False,0.0,tt6269996,15383,<bound method DataFrame.reset_index of ...,15383,15383,<bound method DataFrame.reset_index of ...
15384,none,Adapted from Issue #1 of Frank Miller's semina...,NOT RATED,True,English,The Dark Knight Returns: An Epic Fan Film,USA,Wyatt Weed,0.0,0.0,...,46 min,movie,https://images-na.ssl-images-amazon.com/images...,0.0,tt6274696,15384,<bound method DataFrame.reset_index of ...,15384,15384,<bound method DataFrame.reset_index of ...
15385,none,Lone passengers are traveling to join their lo...,False,True,English,Come Together,USA,Wes Anderson,0.0,7.6,...,4 min,movie,False,38.0,tt6282412,15385,<bound method DataFrame.reset_index of ...,15385,15385,<bound method DataFrame.reset_index of ...
15386,none,False,False,True,English,Binge,USA,Yuri Baranovsky; Angela Gulner,0.0,0.0,...,False,movie,https://images-na.ssl-images-amazon.com/images...,0.0,tt6284550,15386,<bound method DataFrame.reset_index of ...,15386,15386,<bound method DataFrame.reset_index of ...