# Question 2 Part 2

In [2]:
import csv
import pandas as pd
from pandas import DataFrame
import numpy as np
import calendar

In [5]:
# Reading the csv File
dfa=pd.read_csv(r'C:\Users\smrut\Documents\Python\PythonAssignment3\Assignment 3\Data\employee_compensation.csv',sep=",")
dfa.head()

,Year Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,...,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Calendar,2013,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
1,Fiscal,2015,4,Community Health,DPH,Public Health,790.0,"SEIU - Miscellaneous, Local 1021",2600,Dietary & Food,...,52950,69169.82,755.02,4179.08,74103.92,15641.92,12499.30,5669.02,33810.24,107914.16
2,Calendar,2016,3,Human Welfare & Neighborhood Development,WOM,Department of the Status of Women,323.0,Members of Boards and Commissions,0900,Management,...,33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,6,General Administration & Finance,HRD,Human Resources,790.0,"SEIU - Miscellaneous, Local 1021",8100,Legal & Court,...,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
4,Fiscal,2015,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,15849,1102.50,0.00,0.00,1102.50,0.00,538.82,85.36,624.18,1726.68

In [8]:
# Filtering by the year type Calendar
dfb=dfa[dfa['Year Type']=='Calendar']
dfb.head()

,Year Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,...,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Calendar,2013,2,"Public Works, Transportation & Commerce",AIR,Airport Commission,38.0,"Plumbers and Pipefitters, Local 38",7300,Journeyman Trade,...,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
2,Calendar,2016,3,Human Welfare & Neighborhood Development,WOM,Department of the Status of Women,323.0,Members of Boards and Commissions,0900,Management,...,33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,6,General Administration & Finance,HRD,Human Resources,790.0,"SEIU - Miscellaneous, Local 1021",8100,Legal & Court,...,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
5,Calendar,2016,2,"Public Works, Transportation & Commerce",DBI,Department of Building Inspection,790.0,"SEIU - Miscellaneous, Local 1021",1400,"Clerical, Secretarial & Steno",...,23930,80207.24,2232.53,1568.00,84007.77,15064.98,13890.29,6888.51,35843.78,119851.55
7,Calendar,2014,6,General Administration & Finance,ADM,General Services Agency - City Admin,790.0,"SEIU - Miscellaneous, Local 1021",9900,Public Service Aide,...,38054,24180.00,0.00,0.00,24180.00,1490.20,8586.13,1880.37,11956.70,36136.70

In [11]:
#Calculating the Mean by grouping the Dataframe based on Job Family and Employee Identifier
dfc=dfb.groupby(['Job Family','Employee Identifier']).mean().reset_index()
dfc.head()

,Job Family,Employee Identifier,Year,Organization Group Code,Union Code,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Administrative & Mgmt (Unrep),2321,2014.5,6.0,556.0,291241.175,0.0,0.0,291241.175,57103.3575,13071.9925,19095.6025,89270.9525,380512.1275
1,Administrative & Mgmt (Unrep),4800,2016.0,2.0,351.0,14463.000,0.0,0.0,14463.000,2636.6100,1543.3700,1857.4400,6037.4200,20500.4200
2,Administrative & Mgmt (Unrep),5547,2016.0,6.0,351.0,205073.100,0.0,0.0,205073.100,36761.3900,12089.6900,29617.8400,78468.9200,283542.0200
3,Administrative & Mgmt (Unrep),5662,2016.0,6.0,351.0,128370.200,0.0,0.0,128370.200,23089.5500,3601.1900,5032.4800,31723.2200,160093.4200
4,Administrative & Mgmt (Unrep),8493,2016.0,6.0,351.0,53658.000,0.0,0.0,53658.000,9524.3400,4630.1000,6796.6700,20951.1100,74609.1100

In [34]:
#

dfc['GreaterThan%percentOfSal']=dfc['Overtime']>0.05*dfc['Salaries']

KeyError: 'Overtime'

In [16]:
dfd=dfc[dfc.Overtime > 5]
dfd

,Job Family,Employee Identifier,Year,Organization Group Code,Union Code,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
3026,"Clerical, Secretarial & Steno",355,2016.000000,6.0,790.0,541.450000,11.986979,0.000000,892.870000,0.000,167.200000,69.300000,236.500000,1129.370000
3028,"Clerical, Secretarial & Steno",395,2014.000000,6.0,790.0,528.190000,9.992305,0.000000,806.960000,0.000,169.460000,62.480000,231.940000,1038.900000
3089,"Clerical, Secretarial & Steno",1566,2016.000000,6.0,790.0,504.690000,13.671519,0.000000,852.920000,0.000,160.770000,66.200000,226.970000,1079.890000
3095,"Clerical, Secretarial & Steno",1710,2016.000000,6.0,790.0,635.910000,10.858063,40.000000,1114.990000,0.000,202.570000,86.540000,289.110000,1404.100000
3106,"Clerical, Secretarial & Steno",1906,2016.000000,6.0,790.0,504.690000,13.671519,0.000000,852.920000,0.000,160.770000,66.200000,226.970000,1079.890000
3111,"Clerical, Secretarial & Steno",2098,2014.500000,6.0,790.0,657.017500,11.611015,0.000000,1158.232500,0.000,208.007500,89.785000,297.792500,1456.025000
3119,"Clerical, Secretarial & Steno",2397,2014.000000,6.0,790.0,703.000000,7.064420,0.000000,1052.130000,0.000,232.230000,81.460000,313.690000,1365.820000
3191,"Clerical, Secretarial & Steno",3909,2014.333333,6.0,790.0,490.670000,17.376715,0.000000,909.026667,0.000,157.800000,70.413333,228.213333,1137.240000
3202,"Clerical, Secretarial & Steno",4025,2016.000000,6.0,790.0,514.790000,12.854670,0.000000,855.450000,0.000,163.980000,66.400000,230.380000,1085.830000
3211,"Clerical, Secretarial & Steno",4122,2013.000000,6.0,790.0,378.480000,20.299188,0.000000,669.260000,0.000,122.600000,51.810000,174.410000,843.670000
3231,"Clerical, Secretarial & Steno",4551,2016.000000,6.0,790.0,499.800000,13.755402,0.000000,843.410000,0.000,154.330000,65.460000,219.790000,1063.200000
3248,"Clerical, Secretarial & Steno",4877,2016.000000,6.0,790.0,499.800000,7.503201,0.000000,687.230000,0.000,154.330000,53.350000,207.680000,894.910000
3255,"Clerical, Secretarial & Steno",4961,2016.000000,6.0,790.0,459.320000,20.434188,0.000000,890.430000,0.000,144.690000,69.110000,213.800000,1104.230000
3280,"Clerical, Secretarial & Steno",5379,2016.000000,6.0,790.0,504.690000,13.968718,0.000000,860.490000,0.000,160.770000,66.790000,227.560000,1088.050000
3297,"Clerical, Secretarial & Steno",5869,2013.000000,6.0,790.0,553.880000,7.221716,0.000000,775.430000,0.000,179.420000,60.040000,239.460000,1014.890000
3341,"Clerical, Secretarial & Steno",6579,2014.000000,6.0,790.0,528.190000,12.621840,0.000000,880.320000,0.000,169.460000,68.160000,237.620000,1117.940000
3354,"Clerical, Secretarial & Steno",6899,2015.500000,6.0,790.0,570.295000,10.707135,0.000000,918.530000,0.000,174.005000,71.290000,245.295000,1163.825000
3358,"Clerical, Secretarial & Steno",6977,2014.000000,6.0,790.0,557.530000,10.148318,0.000000,872.980000,0.000,178.880000,67.590000,246.470000,1119.450000
3362,"Clerical, Secretarial & Steno",7088,2014.500000,6.0,790.0,465.975000,16.143814,0.000000,816.510000,0.000,144.465000,63.290000,207.755000,1024.265000
3368,"Clerical, Secretarial & Steno",7185,2016.000000,6.0,790.0,931.600000,7.974388,0.000000,1623.680000,0.000,292.600000,126.020000,418.620000,2042.300000
3378,"Clerical, Secretarial & Steno",7347,2014.000000,6.0,790.0,456.000000,14.391447,0.000000,755.250000,0.000,150.630000,58.470000,209.100000,964.350000
3398,"Clerical, Secretarial & Steno",7654,2015.000000,6.0,790.0,1058.270000,5.216104,0.000000,1642.440000,0.000,332.986667,127.376667,460.363333,2102.803333
3417,"Clerical, Secretarial & Steno",7990,2015.000000,6.0,790.0,687.920000,11.556934,0.000000,1234.833333,0.000,216.876667,95.746667,312.623333,1547.456667
3433,"Clerical, Secretarial & Steno",8172,2016.000000,6.0,790.0,374.850000,14.449958,0.000000,577.890000,0.000,115.750000,44.850000,160.600000,738.490000
3536,"Clerical, Secretarial & Steno",10352,2015.500000,6.0,790.0,460.755000,17.576236,0.000000,833.890000,0.000,139.090000,64.715000,203.805000,1037.695000
3544,"Clerical, Secretarial & Steno",10479,2016.000000,6.0,790.0,499.800000,13.130102,0.000000,827.790000,0.000,154.330000,64.250000,218.580000,1046.370000
3582,"Clerical, Secretarial & Steno",11093,2014.000000,6.0,790.0,456.000000,14.049034,0.000000,748.130000,0.000,150.630000,57.920000,208.550000,956.680000
3593,"Clerical, Secretarial & Steno",11358,2014.800000,6.0,790.0,683.334000,6.268185,0.000000,976.024000,0.000,208.706000,75.668000,284.374000,1260.398000
3628,"Clerical, Secretarial & Steno",12052,2016.000000,6.0,790.0,348.820000,24.389484,0.000000,645.580000,0.000,107.710000,50.110000,157.820000,803.400000
3634,"Clerical, Secretarial & Steno",12081,2013.500000,6.0,790.0,733.110000,7.461528,0.000000,1134.130000,0.000,237.925000,87.805000,325.730000,1459.860000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27416,Nursing,15281,2013.500000,4.0,791.0,321.355000,249.647435,9496.200000,12395.640000,0.000,21.600000,959.670000,981.270000,13376.910000
28118,Nursing,22315,2013.000000,4.0,791.0,0.000000,inf,3364.750000,4071.150000,170.390,0.000000,1427.060000,1597.450000,5668.600000
28635,Nursing,27112,2014.000000,4.0,791.0,3631.460000,7.952365,13526.526667,27645.170000,0.000,69.726667,4716.996667,4786.723333,32431.893333
28796,Nursing,28530,2013.000000,4.0,791.0,989.100000,6.824462,32.970000,1689.720000,-0.010,0.000000,957.660000,957.650000,2647.370000
29307,Nursing,33596,2014.500000,4.0,791.0,2300.245000,15.438540,12145.947500,22614.920000,0.000,201.110000,1751.582500,1952.692500,24567.612500
30526,Nursing,45582,2014.500000,4.0,791.0,695.077500,128.834420,13426.470000,20345.960000,0.000,0.000000,1608.702500,1608.702500,21954.662500
30918,Nursing,49171,2013.000000,4.0,791.0,1852.510000,27.166700,13129.150000,24304.710000,0.000,146.590000,1881.670000,2028.260000,26332.970000
32840,Personnel,3593,2014.000000,6.0,790.0,280.926667,5.435476,0.000000,323.823333,0.000,74.040000,25.073333,99.113333,422.936667
41884,Public Service Aide,12573,2013.000000,6.0,790.0,437.390000,19.307406,21.590000,828.350000,0.000,140.540000,64.130000,204.670000,1033.020000
43508,Public Service Aide,29838,2014.500000,6.0,790.0,158.000000,42.248838,12.840000,276.310000,0.000,49.000000,21.390000,70.390000,346.700000
43606,Public Service Aide,30820,2015.000000,6.0,790.0,171.480000,34.803143,6.500000,280.320000,0.000,56.750000,21.700000,78.450000,358.770000
50398,Street Transit,2521,2015.000000,2.0,253.0,605.530000,6.193092,0.000000,832.610000,171.360,0.000000,65.770000,237.130000,1069.740000
50702,Street Transit,6545,2015.000000,2.0,253.0,454.150000,5.504910,0.000000,567.690000,111.220,0.000000,44.960000,156.180000,723.870000
50739,Street Transit,6934,2015.000000,2.0,253.0,605.540000,6.192888,0.000000,832.620000,148.300,0.000000,65.940000,214.240000,1046.860000
50747,Street Transit,7001,2015.000000,2.0,253.0,302.770000,12.385776,0.000000,416.310000,74.150,95.580000,32.310000,202.040000,618.350000
50969,Street Transit,9743,2015.000000,2.0,253.0,605.540000,6.192888,0.000000,832.620000,171.370,0.000000,65.770000,237.140000,1069.760000
51067,Street Transit,11117,2014.500000,2.0,253.0,832.615000,5.322773,125.000000,1326.615000,235.630,274.950000,93.030000,603.610000,1930.225000
51361,Street Transit,15019,2015.000000,2.0,253.0,302.760000,12.386594,0.000000,416.300000,85.680,0.000000,32.890000,118.570000,534.870000
51643,Street Transit,18646,2014.000000,2.0,253.0,340.620000,9.786076,0.000000,454.160000,96.400,0.000000,35.890000,132.290000,586.450000
51923,Street Transit,21987,2015.000000,2.0,253.0,151.380000,24.773188,0.000000,208.150000,42.840,0.000000,16.450000,59.290000,267.440000
51929,Street Transit,22040,2014.500000,2.0,253.0,378.460000,5.945251,125.000000,588.615000,107.105,142.655000,35.895000,285.655000,874.270000
52190,Street Transit,25572,2014.000000,2.0,253.0,151.380000,24.773188,0.000000,208.150000,42.840,0.000000,16.450000,59.290000,267.440000
52339,Street Transit,27458,2015.000000,2.0,253.0,151.380000,24.773188,0.000000,208.150000,42.840,0.000000,16.450000,59.290000,267.440000
53601,Street Transit,43780,2014.000000,2.0,253.0,908.310000,5.504668,0.000000,1362.460000,257.050,301.270000,105.480000,663.800000,2026.260000
53688,Street Transit,44961,2015.000000,2.0,253.0,605.540000,6.192888,0.000000,832.620000,171.370,0.000000,65.770000,237.140000,1069.760000
53689,Street Transit,44969,2014.000000,2.0,253.0,454.150000,8.257366,0.000000,624.460000,128.520,150.630000,48.340000,327.490000,951.950000
53868,Street Transit,47411,2015.000000,2.0,253.0,454.150000,5.504910,0.000000,567.690000,128.520,143.350000,43.950000,315.820000,883.510000
53954,Street Transit,48556,2015.000000,2.0,253.0,302.770000,12.385776,0.000000,416.310000,85.680,95.580000,32.230000,213.490000,629.800000
54114,Street Transit,50641,2015.000000,2.0,253.0,454.150000,8.257366,0.000000,624.460000,111.220,0.000000,49.460000,160.680000,785.140000
54244,Street Transit,52122,2015.000000,2.0,253.0,454.150000,8.257366,0.000000,624.460000,128.520,0.000000,49.330000,177.850000,802.310000

In [19]:
dfe=dfd.groupby('Job Family')['Total Benefits','Total Compensation'].mean().reset_index()
dfe.head()

                      Job Family  Total Benefits  Total Compensation
0  Clerical, Secretarial & Steno      256.885681         1187.515340
1         Correction & Detention       96.543333         1379.143333
2                 Dietary & Food      400.375000         1769.750000
3               Journeyman Trade      117.955000          768.040000
4                        Nursing     1815.886042        16093.024792

In [23]:
dfe['Percent_Total_Benefit']=(dfe['Total Benefits']/dfe['Total Compensation'])*100
dfe

,Job Family,Total Benefits,Total Compensation,Percent_Total_Benefit
0,"Clerical, Secretarial & Steno",256.885681,1187.515340,21.632199
1,Correction & Detention,96.543333,1379.143333,7.000239
2,Dietary & Food,400.375000,1769.750000,22.623252
3,Journeyman Trade,117.955000,768.040000,15.357924
4,Nursing,1815.886042,16093.024792,11.283684
5,Personnel,99.113333,422.936667,23.434557
6,Public Service Aide,117.836667,579.496667,20.334313
7,Street Transit,234.789211,863.444474,27.192161

In [26]:
result=dfe.sort('Percent_Total_Benefit',ascending=False).reset_index()
result

C:\Users\smrut\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,index,Job Family,Total Benefits,Total Compensation,Percent_Total_Benefit
0,7,Street Transit,234.789211,863.444474,27.192161
1,5,Personnel,99.113333,422.936667,23.434557
2,2,Dietary & Food,400.375000,1769.750000,22.623252
3,0,"Clerical, Secretarial & Steno",256.885681,1187.515340,21.632199
4,6,Public Service Aide,117.836667,579.496667,20.334313
5,3,Journeyman Trade,117.955000,768.040000,15.357924
6,4,Nursing,1815.886042,16093.024792,11.283684
7,1,Correction & Detention,96.543333,1379.143333,7.000239

In [27]:
result.to_csv(r'C:\Users\smrut\Documents\Python\PythonAssignment3\Assignment 3\Q2Part2Result.csv', sep=',')